export const CONTRACT = {
  resources: {
    Product: {
      view: "v_chatbot_products",
      description: "Read-model sản phẩm dành riêng cho chatbot",
      aliases: ["product", "sản phẩm", "sp", "san pham", "hàng", "đồ"],
      fields: {
        id: { type: "uuid", description: "Mã sản phẩm" },
        name: { type: "text", description: "Tên sản phẩm" },
        slug: { type: "text", description: "Slug URL" },
        description: { type: "text", description: "Mô tả sản phẩm" },
        origin_price: { type: "number", description: "Giá gốc (VNĐ)" },
        min_price: { type: "number", description: "Giá thấp nhất" },
        max_price: { type: "number", description: "Giá cao nhất" },
        total_stock: { type: "number", description: "Tổng tồn kho" },
        avg_rating: { type: "number", description: "Điểm đánh giá trung bình" },
        review_count: { type: "number", description: "Số lượt đánh giá" },
        main_image_url: { type: "text", description: "Ảnh chính" },
        spec_summary: { type: "text", description: "Thông số đã gộp" },
        status: { type: "text", description: "Trạng thái sản phẩm" },
        is_featured: { type: "boolean", description: "Sản phẩm nổi bật" },
        category_id: { type: "uuid", description: "Mã danh mục" },
        category_name: { type: "text", description: "Tên danh mục" },
        brand_id: { type: "uuid", description: "Mã thương hiệu" },
        brand_name: { type: "text", description: "Tên thương hiệu" },
        created_at: { type: "timestamp", description: "Ngày tạo" },
      },
      defaultSelect: ["id", "name", "min_price", "total_stock", "category_name"],
      filterable: true,
      sortable: true,
      relations: {
        Category: {
          type: "left",
          localField: "category_id",
          foreignResource: "Category",
          foreignField: "id",
          alias: "c",
        },
        Brand: {
          type: "left",
          localField: "brand_id",
          foreignResource: "Brand",
          foreignField: "id",
          alias: "b",
        },
      },
    },

    ProductVariant: {
      view: "v_chatbot_product_variants",
      description: "Read-model biến thể sản phẩm dành riêng cho chatbot",
      aliases: ["variant", "biến thể", "phiên bản", "cấu hình", "sku"],
      fields: {
        id: { type: "uuid", description: "Mã biến thể" },
        product_id: { type: "uuid", description: "Mã sản phẩm cha" },
        product_name: { type: "text", description: "Tên sản phẩm cha" },
        product_slug: { type: "text", description: "Slug sản phẩm cha" },
        category_id: { type: "uuid", description: "Mã danh mục" },
        category_name: { type: "text", description: "Tên danh mục" },
        brand_id: { type: "uuid", description: "Mã thương hiệu" },
        brand_name: { type: "text", description: "Tên thương hiệu" },
        sku: { type: "text", description: "Mã SKU" },
        display_name: { type: "text", description: "Tên hiển thị biến thể" },
        variant_signature: { type: "text", description: "Chữ ký biến thể" },
        attribute_summary: { type: "text", description: "Thuộc tính đã gộp" },
        price: { type: "number", description: "Giá bán thực tế" },
        compare_at_price: { type: "number", description: "Giá so sánh" },
        stock_quantity: { type: "number", description: "Số lượng tồn kho" },
        status: { type: "boolean", description: "Đang hoạt động" },
        created_at: { type: "timestamp", description: "Ngày tạo" },
      },
      defaultSelect: [
        "id",
        "product_name",
        "display_name",
        "price",
        "stock_quantity",
      ],
      filterable: true,
      sortable: true,
      relations: {
        Product: {
          type: "left",
          localField: "product_id",
          foreignResource: "Product",
          foreignField: "id",
          alias: "p",
        },
      },
    },

    Category: {
      view: "categories",
      description: "Danh mục sản phẩm",
      aliases: ["category", "danh mục", "loại", "nhóm hàng", "danh_muc"],
      fields: {
        id: { type: "uuid", description: "Mã danh mục" },
        name: { type: "text", description: "Tên danh mục" },
        slug: { type: "text", description: "Slug URL" },
        parent_id: { type: "uuid", description: "Mã danh mục cha" },
        sort_order: { type: "number", description: "Thứ tự sắp xếp" },
        status: { type: "boolean", description: "Đang hiển thị" },
        created_at: { type: "timestamp", description: "Ngày tạo" },
      },
      defaultSelect: ["id", "name", "slug"],
      filterable: true,
      sortable: true,
    },

    Brand: {
      view: "brands",
      description: "Thương hiệu sản phẩm",
      aliases: ["brand", "thương hiệu", "hãng", "nhà sản xuất", "hang"],
      fields: {
        id: { type: "uuid", description: "Mã thương hiệu" },
        name: { type: "text", description: "Tên thương hiệu" },
        slug: { type: "text", description: "Slug URL" },
        logo_url: { type: "text", description: "URL logo" },
      },
      defaultSelect: ["id", "name"],
      filterable: true,
      sortable: true,
    },

    Coupon: {
      view: "coupons",
      description: "Mã giảm giá / voucher khuyến mãi",
      aliases: [
        "coupon",
        "voucher",
        "mã giảm giá",
        "khuyến mãi",
        "km",
        "mã khuyến mãi",
      ],
      fields: {
        id: { type: "uuid", description: "Mã coupon" },
        code: { type: "text", description: "Mã code" },
        discount_type: { type: "text", description: "Loại giảm" },
        discount_value: { type: "number", description: "Giá trị giảm" },
        min_order_value: { type: "number", description: "Giá trị đơn tối thiểu" },
        max_discount_amount: { type: "number", description: "Giảm tối đa" },
        usage_limit: { type: "number", description: "Giới hạn lượt dùng" },
        used_count: { type: "number", description: "Đã dùng" },
        start_date: { type: "timestamp", description: "Ngày bắt đầu" },
        end_date: { type: "timestamp", description: "Ngày kết thúc" },
        status: { type: "text", description: "Trạng thái coupon" },
        is_public: { type: "boolean", description: "Voucher public" },
      },
      defaultSelect: [
        "code",
        "discount_type",
        "discount_value",
        "end_date",
        "status",
      ],
      filterable: true,
      sortable: true,
    },

    FlashSaleItem: {
      view: "v_chatbot_flash_sale_items",
      description: "Biến thể sản phẩm đang nằm trong chương trình flash sale",
      aliases: [
        "flash sale",
        "flash sale item",
        "flash sale items",
        "deal",
        "giảm giá sốc",
        "deal sốc",
        "sale sốc",
      ],
      fields: {
        flash_sale_id: { type: "uuid", description: "Mã chương trình flash sale" },
        sale_name: { type: "text", description: "Tên chương trình flash sale" },
        sale_status: { type: "text", description: "Trạng thái flash sale" },
        start_time: { type: "timestamp", description: "Thời gian bắt đầu" },
        end_time: { type: "timestamp", description: "Thời gian kết thúc" },
        variant_id: { type: "uuid", description: "Mã biến thể" },
        product_id: { type: "uuid", description: "Mã sản phẩm" },
        product_name: { type: "text", description: "Tên sản phẩm" },
        product_slug: { type: "text", description: "Slug sản phẩm" },
        category_name: { type: "text", description: "Tên danh mục" },
        brand_name: { type: "text", description: "Tên thương hiệu" },
        display_name: { type: "text", description: "Tên hiển thị biến thể" },
        attribute_summary: { type: "text", description: "Thuộc tính biến thể" },
        flash_price: { type: "number", description: "Giá flash sale" },
        flash_stock: { type: "number", description: "Tồn kho flash sale" },
        sold_count: { type: "number", description: "Đã bán" },
      },
      defaultSelect: [
        "sale_name",
        "product_name",
        "display_name",
        "flash_price",
        "flash_stock",
        "end_time",
      ],
      filterable: true,
      sortable: true,
    },

    FlashSale: {
      view: "flash_sales",
      description: "Chương trình flash sale",
      aliases: ["flash sale", "deal", "giảm giá sốc", "deal sốc"],
      fields: {
        id: { type: "uuid", description: "Mã flash sale" },
        name: { type: "text", description: "Tên chương trình" },
        description: { type: "text", description: "Mô tả" },
        start_time: { type: "timestamp", description: "Thời gian bắt đầu" },
        end_time: { type: "timestamp", description: "Thời gian kết thúc" },
        status: { type: "text", description: "Trạng thái flash sale" },
      },
      defaultSelect: ["id", "name", "start_time", "end_time", "status"],
      filterable: true,
      sortable: true,
    },

    Order: {
      view: "v_chatbot_orders",
      description: "Read-model đơn hàng của khách dùng cho chatbot",
      aliases: [
        "order",
        "đơn hàng",
        "don hang",
        "mã đơn",
        "ma don",
        "order number",
      ],
      fields: {
        user_id: { type: "uuid", description: "Mã người dùng" },
        user_email: { type: "text", description: "Email người dùng" },
        order_id: { type: "uuid", description: "Mã đơn hàng" },
        order_number: { type: "text", description: "Mã đơn hàng hiển thị" },
        created_at: { type: "timestamp", description: "Thời gian tạo đơn" },
        order_status: { type: "text", description: "Trạng thái đơn hàng" },
        payment_status: { type: "text", description: "Trạng thái thanh toán" },
        tracking_code: { type: "text", description: "Mã vận đơn" },
        subtotal: { type: "number", description: "Tạm tính" },
        shipping_fee: { type: "number", description: "Phí vận chuyển" },
        discount_amount: { type: "number", description: "Tiền giảm" },
        total_amount: { type: "number", description: "Tổng thanh toán" },
        item_count: { type: "number", description: "Số lượng dòng sản phẩm" },
        item_summary: { type: "text", description: "Tóm tắt sản phẩm trong đơn" },
      },
      defaultSelect: [
        "order_number",
        "created_at",
        "order_status",
        "payment_status",
        "total_amount",
        "item_count",
      ],
      filterable: true,
      sortable: true,
    },

    Article: {
      view: "articles",
      description: "Bài viết công nghệ / tin tức",
      aliases: ["article", "bài viết", "tin tức", "blog", "tin công nghệ"],
      fields: {
        id: { type: "uuid", description: "Mã bài viết" },
        title: { type: "text", description: "Tiêu đề" },
        slug: { type: "text", description: "Slug URL" },
        is_published: { type: "boolean", description: "Đã xuất bản" },
        created_at: { type: "timestamp", description: "Ngày tạo" },
      },
      defaultSelect: ["id", "title", "slug", "created_at"],
      filterable: true,
      sortable: true,
    },
  },
};
